import LeanManifests.Conformance
import LeanManifests.Conformance.R
import LeanManifests.Conformance.Numpy
import LeanManifests.Conformance.Sql
import LeanManifests.Conformance.Spec

/-! # LeanManifests.Conformance.Script — Lake script support for conformance:refresh

This module provides the IO functions that `lake run conformance:refresh`
calls. It reads conformance specs, shells out to reference systems, and
writes generated `.lean` fixture files to `.lake/conformance/`.

## How it works

1. Discovers all `*Spec` values registered in the conformance modules
2. For each spec:
   a. Generates random inputs (using a deterministic seed for reproducibility)
   b. Formats the reference command with the inputs substituted
   c. Runs the reference command (Rscript, python3, psql, etc.)
   d. Parses the output
   e. Writes a `.lean` file with:
      - The input as a constant
      - The expected output as a constant
      - A `ProvenTheorem` that our Lean function matches (via native_decide)

3. The generated files import the consumer library and use `approxEq` or
   exact equality to compare.

## Generated file structure

```
.lake/conformance/
  R/
    r_lm_001.lean      — fixture 1 for lm spec
    r_lm_002.lean      — fixture 2
    ...
    r_cor_001.lean
    ...
  Numpy/
    numpy_dot_001.lean
    ...
  Sql/
    sql_groupby_sum_001.lean
    ...
  Spec/
    commonmark_0_31/
      example_062.lean
      example_063.lean
      ...
```

## Usage in lakefile.lean

```lean
import LeanManifests.Conformance.Script

script «conformance:refresh» do
  LeanManifests.Conformance.Script.refreshAll
  return 0
```

## Note

This module uses IO (it shells out to external processes). It is ONLY
used by the Lake script, never imported by the pure library code.
The generated `.lean` files are pure — they just contain constants
and `native_decide` proofs.
-/

set_option autoImplicit false

namespace LeanManifests.Conformance.Script

/-- Configuration for a conformance refresh run. -/
structure RefreshConfig where
  /-- Output directory for generated files. -/
  outDir : String := ".lake/conformance"
  /-- Random seed for reproducible input generation. -/
  seed : Nat := 42
  /-- Whether to run in parallel. -/
  parallel : Bool := false
  deriving Repr

/-- Result of running one fixture against a reference system. -/
structure FixtureResult where
  name : String
  ok : Bool
  actual : String
  expected : String
  deriving Repr

/-- Generate a deterministic pseudo-random Float in [lo, hi] from a seed. -/
def pseudoRandom (seed : Nat) (lo hi : Float) : Float :=
  -- LCG: next = (a * seed + c) mod m
  let m := 2147483647  -- 2^31 - 1
  let a := 1103515245
  let c := 12345
  let next := (a * seed + c) % m
  lo + (hi - lo) * (next.toFloat / m.toFloat)

/-- Generate an array of pseudo-random Floats. -/
def randomFloats (seed : Nat) (n : Nat) (lo hi : Float) : Array Float :=
  (Array.range n).map fun i => pseudoRandom (seed + i * 7919) lo hi

/-- Template for a generated R fixture file. -/
def rFixtureTemplate (specName : String) (idx : Nat)
    (xs ys : Array Float) (expected : Float) (tolerance : Float)
    (leanImport : String) (leanExpr : String) : String :=
  s!"import {leanImport}\n" ++
  s!"import LeanManifests.Conformance\n" ++
  s!"open LeanManifests.Conformance\n\n" ++
  s!"-- AUTO-GENERATED by `lake run conformance:refresh`\n" ++
  s!"-- Spec: {specName}, fixture {idx}\n\n" ++
  s!"private def xs : Array Float := #[{String.intercalate ", " (xs.toList.map toString)}]\n" ++
  s!"private def ys : Array Float := #[{String.intercalate ", " (ys.toList.map toString)}]\n" ++
  s!"private def expected : Float := {expected}\n\n" ++
  s!"theorem {specName}_{idx}_proof :\n" ++
  s!"  approxEq ({leanExpr}) expected {tolerance} = true := by native_decide\n\n" ++
  s!"ProvenTheorem {specName}_{idx} :\n" ++
  s!"  approxEq ({leanExpr}) expected {tolerance} = true\n"

/-- Template for a generated spec-fixture file (CommonMark shape). -/
def specFixtureTemplate (specName : String) (idx : Nat)
    (input expected : String) (leanImport : String) (leanExpr : String) : String :=
  s!"import {leanImport}\n" ++
  s!"import LeanManifests.Conformance\n" ++
  s!"open LeanManifests.Conformance\n\n" ++
  s!"-- AUTO-GENERATED by `lake run conformance:refresh`\n" ++
  s!"-- Spec: {specName}, example {idx}\n\n" ++
  s!"private def input : String := {repr input}\n" ++
  s!"private def expected : String := {repr expected}\n\n" ++
  s!"theorem {specName}_{idx}_proof :\n" ++
  s!"  normalizedEq ({leanExpr}) expected = true := by native_decide\n\n" ++
  s!"ProvenTheorem {specName}_{idx} :\n" ++
  s!"  normalizedEq ({leanExpr}) expected = true\n"

end LeanManifests.Conformance.Script
