import LeanManifests.Conformance

/-! # LeanManifests.Conformance.Spec — conformance harness for spec-fixture systems

Shape: string in, string out (exact or normalized match).
Reference: a spec file (JSON, YAML, or custom format) containing
           input/expected pairs. No external process needed at runtime —
           the spec IS the reference.

## Why this is a different shape

R/numpy/SQL conformance requires running an external process to get the
expected output. Spec-fixture conformance has the expected output already
written down in a file (by the spec authors). The "reference system" is
the spec document itself.

## Systems that fit this shape

- **CommonMark** — `spec.json` with markdown → HTML pairs
- **HTML spec** — parsing test fixtures
- **JSON Schema** — validation test suite
- **RFC test vectors** — crypto, encoding, protocol conformance
- **Unicode** — normalization test data, grapheme break tests
- **CSV RFC 4180** — parsing edge cases

## The pattern

1. A spec file exists (e.g. `spec.json` with 652 examples)
2. ONE example is checked in as a golden fixture (ProvenTheorem)
3. The bulk fixtures are generated by reading the spec file at
   `lake run conformance:refresh` time and writing individual
   Lean theorems to `.lake/conformance/Spec/<name>/`

## Golden fixture example: CommonMark ATX heading
-/

set_option autoImplicit false

namespace LeanManifests.Conformance.Spec
open LeanManifests.Conformance

-- ════════════════════════════════════════════════════════════
-- § Spec-fixture helpers
-- ════════════════════════════════════════════════════════════

/-- A single spec example: input string → expected output string. -/
structure SpecExample where
  /-- Section of the spec (e.g. "ATX headings"). -/
  section_ : String
  /-- Example number in the spec. -/
  example_ : Nat
  /-- Input (e.g. markdown source). -/
  input : String
  /-- Expected output (e.g. HTML). -/
  expected : String
  deriving Repr

/-- Standard fixture metadata for a spec conformance check. -/
def specFixture (name : String) (specName : String) (version : String) : Fixture :=
  { name
    reference := .commonmark version
    command := s!"(from {specName} spec v{version})"
    mode := .normalized }

-- ════════════════════════════════════════════════════════════
-- § Golden fixture: CommonMark ATX heading
-- ════════════════════════════════════════════════════════════

/-- CommonMark spec example 62: simple ATX heading.
    ```
    # foo
    ```
    →
    ```
    <h1>foo</h1>
    ```
-/
def cm_atx_heading : SpecExample :=
  { section_ := "ATX headings"
    example_ := 62
    input := "# foo\n"
    expected := "<h1>foo</h1>\n" }

def cm_atx_golden : Fixture := specFixture "cm_atx_heading" "CommonMark" "0.31"

-- ════════════════════════════════════════════════════════════
-- § Golden fixture: CommonMark emphasis
-- ════════════════════════════════════════════════════════════

/-- CommonMark spec example 350: simple emphasis.
    ```
    *foo bar*
    ```
    →
    ```
    <p><em>foo bar</em></p>
    ```
-/
def cm_emphasis : SpecExample :=
  { section_ := "Emphasis and strong emphasis"
    example_ := 350
    input := "*foo bar*\n"
    expected := "<p><em>foo bar</em></p>\n" }

-- ════════════════════════════════════════════════════════════
-- § Spec template (for bulk generation from spec.json)
-- ════════════════════════════════════════════════════════════

/-- Supported spec file formats. -/
inductive SpecFormat where
  /-- JSON array of {section, example, markdown, html} objects (CommonMark). -/
  | commonmarkJson
  /-- JSON array of {input, expected} objects (generic). -/
  | genericJson
  /-- One file per test case in a directory (e.g. tree-sitter corpus). -/
  | directory
  deriving Repr

/-- A spec-fixture conformance spec. Points at a spec file and
    describes how to parse it into SpecExample values. -/
structure SpecFileSpec where
  /-- Name of this conformance suite. -/
  name : String
  /-- Path to the spec file (relative to project root). -/
  specFile : String
  /-- Format of the spec file. -/
  format : SpecFormat
  /-- Optional: only test examples from these sections. -/
  sections : Option (Array String) := none
  deriving Repr

/-- Example: CommonMark spec suite. -/
def commonmark_spec : SpecFileSpec :=
  { name := "commonmark_0_31"
    specFile := "vendor/commonmark-spec/spec.json"
    format := .commonmarkJson }

end LeanManifests.Conformance.Spec
